env:
  global:
    - CODECOV_TOKEN=b040177c-c3c6-4607-aeaa-7e85545b708f
language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: klindziukp-github
    token:
      secure: gCLMc/PcPSbTyB/iYSHEqckVq2IpUpLZFEQZfzMejT1rc+EZor1s7mrkkJP0qzJsCG+3R5U5vyPKvMKbfwY55tZXoaWKYmJ55zCeaZngj3IVFFUCQ6zLVCujzQcwAjTDfHuzhmzM9TPp8XAnNXKcOubsD3330ECR7W1y1WdhnywQlelNVKIEITZ1x61BhGspikWqeAdY2+YE7HTCS9FOmoISy9TrHEyS0urXXtDbTwJZClA0vRoauoHu5MbHPkDU0KtbNsIkMKJQtHADYtDqPZlJluDoKSUWrjVj9x/uSYGZLqNHj2198R15U1vecw1LF2h393P2MHvb/dth5uCNXJ0+RcxNLLH1J94RLlDf/anFv8h8pNCsxgDxJ7aR147i5qQ3wdfGnXhXRAu7S3E0LEQFk15UBW4tD8sv4c3pOb3WnSb0wzY1OHMvGpS6FjpP05SFbWHvC0bIQDZ+ateG7VcsQeudaq3fQUbJGfZmmz5Izj7ITlD2R+SssRrCosVFDhMjt8YCtyMuyWzah7TNsBka1deV04Stt/PPs+iTpLh5VoP+gAeuDekxN9U21B+NutRD81fGL9dWbqJrtmQvH6hTkGz3aPQjjrFdldd2xGCG/AuqCKZess/5NxM6xnmo3/LlNtzQfvrD67LDADZH4QVZ6uJoUYTtWe5tZfu4PXM=
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build -i --continue
  - ./gradlew sonarqube
after_success:
  - bash <(curl -s https://codecov.io/bash)
