info:
  app:
    name: Evbx Resource service
    description: REST Service for retrievieng ' Resource ' information
    version: 0.0.1-SNAPSHOT
spring:
  redis:
    host: evbx-redis
    port: 6379
  datasource:
    url: jdbc:mysql://evbx-mysql/evbx_resource
    username: root
    password: root
  cache:
    type: redis
server:
  servlet:
    context-path: /v1/evbx
  port: 8002