version: '3.7'

services:
  mysql:
    image: mysql:5.7.24
    container_name: mysql
    volumes:
      - mysqldata:/usr/share/mysql/data
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: evbx_resource
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - database

networks:
  database:

volumes:
  mysqldata:
    driver: local
